# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pairwiseComparisons <- function(entries, n_cores, include_self = FALSE) {
    .Call('_ICIKendallTau_pairwiseComparisons', PACKAGE = 'ICIKendallTau', entries, n_cores, include_self)
}

sortedIndex <- function(x) {
    .Call('_ICIKendallTau_sortedIndex', PACKAGE = 'ICIKendallTau', x)
}

compare_self <- function(x) {
    .Call('_ICIKendallTau_compare_self', PACKAGE = 'ICIKendallTau', x)
}

compare_both <- function(x, y) {
    .Call('_ICIKendallTau_compare_both', PACKAGE = 'ICIKendallTau', x, y)
}

which_notzero <- function(x) {
    .Call('_ICIKendallTau_which_notzero', PACKAGE = 'ICIKendallTau', x)
}

kendall_discordant <- function(x, y) {
    .Call('_ICIKendallTau_kendall_discordant', PACKAGE = 'ICIKendallTau', x, y)
}

count_rank_tie <- function(ranks) {
    .Call('_ICIKendallTau_count_rank_tie', PACKAGE = 'ICIKendallTau', ranks)
}

#' Calculates ici-kendall-tau
#' 
#' Calculates kendall-tau, with consideration of missingness providing information.
#' Uses the calculation of tau-b, and always uses the asymptotic approximation of 
#' the p-value.
#' 
#' @param x numeric vector
#' @param y numeric vector
#' @param perspective should we consider the "local" or "global" perspective?
#' @param alternative what is the alternative for the p-value test?
#' @param continuity logical: if true, a continuity correction is used
#' @param output used to control reporting of values for debugging
#' 
#' @details Calculates the information-content-informed Kendall-tau correlation measure.
#'   This correlation is based on concordant and discordant ranked pairs, like Kendall-tau,
#'   but also includes missing values (as NA). Missing values are assumed to be *primarily* due
#'   to lack of detection due to instrumental sensitivity, and therefore encode *some* information.
#'   
#'   For more details see the ICI-Kendall-tau vignette:
#'   
#'   \code{browseVignettes("ICIKendallTau")}
#' 
#' @examples 
#' x = sort(rnorm(100))
#' y = x + 1
#' y2 = y
#' y2[1:10] = NA
#' ici_kt(x, y)
#' ici_kt(x, y2, "global")
#' ici_kt(x, y2)
#' 
#' @importFrom Rcpp sourceCpp
#' @export
#' @useDynLib ICIKendallTau
#' @return kendall tau correlation, p-value, max-correlation, completeness
ici_kt <- function(x, y, perspective = "local", alternative = "two.sided", continuity = FALSE, output = "simple") {
    .Call('_ICIKendallTau_ici_kt', PACKAGE = 'ICIKendallTau', x, y, perspective, alternative, continuity, output)
}

ici_kt_pairs <- function(x, y, perspective = "local", alternative = "two.sided", output = "simple") {
    .Call('_ICIKendallTau_ici_kt_pairs', PACKAGE = 'ICIKendallTau', x, y, perspective, alternative, output)
}

